Repository xeroxinteractive/config, pull requests merged in 2022-02, with the labels that each got.

#1003 Resolve config path as URL
  packages/xerox-cli/bin/x.js
Labels: approved, release, change: fix

#1012 Remove overenthusiastic TS checking for now
  packages/xerox-eslint-config/typescript.js
Labels: release, change: refactor

#1014 Release revert of TypeScript eslint strict rules
  package.json
  packages/xerox-cli/package.json
  packages/xerox-commitlint-config/package.json
  packages/xerox-eslint-config/package.json
  packages/xerox-eslint-config/typescript.js
  packages/xerox-stylelint-config/package.json
  yarn.lock
Labels: release
