Repository xeroxinteractive/config, pull requests merged in 2022-01, with the labels that each got.

#987 Add save-exact npmrc
  .npmrc
Labels: change: chore

#836 Add ESM support to Xerox CLI (#833)
  .github/dependabot.yml
  .github/workflows/browserslist-stats-cron.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .npmrc
  .nvmrc
  README.md
  __tests__/audit.test.js
  jest-esm-resolver.js
  jest.config.js
  package.json
  packages/xerox-browserslist-config/README.md
  packages/xerox-browserslist-config/package.json
  packages/xerox-cli/package.json
  packages/xerox-cli/source/index.ts
  packages/xerox-commitlint-config/README.md
  packages/xerox-commitlint-config/package.json
  packages/xerox-eslint-config/README.md
  packages/xerox-eslint-config/__tests__/configs.test.js
  packages/xerox-eslint-config/__tests__/fixtures.test.js
  packages/xerox-eslint-config/package.json
  packages/xerox-prettier-config/README.md
  packages/xerox-semantic-release-config/package.json
  packages/xerox-stylelint-config/README.md
  packages/xerox-stylelint-config/package.json
  renovate.json
  yarn.lock
Labels: release

#988 Downgrade normalize-url + auto registry workaround
  lerna.json
  package.json
Labels: release, change: chore

#989 Fix release
  lerna.json
  package.json
Labels: release

#991 Add ESLint TS checking rules + style enforcement
  packages/xerox-eslint-config/typescript.js
Labels: needs review, release, change: feature

#994 Remove build step and go full ESM
  package.json
  packages/xerox-cli/bin/x.js
  packages/xerox-cli/package.json
  packages/xerox-cli/source/index.ts
  packages/xerox-cli/tsconfig.json
  yarn.lock
Labels: approved, release, change: feature

#999 Release
  package.json
  packages/xerox-cli/bin/x.js
  packages/xerox-cli/package.json
  packages/xerox-cli/source/index.ts
  packages/xerox-cli/tsconfig.json
  packages/xerox-commitlint-config/package.json
  packages/xerox-eslint-config/package.json
  packages/xerox-eslint-config/typescript.js
  packages/xerox-semantic-release-config/package.json
  packages/xerox-stylelint-config/package.json
  yarn.lock
Labels: release
